direction: right

yml: docker-compose.yml {
  shape: page
  style.fill: "#ffffff"
  style.stroke: "#333333"
}

up: docker compose up {
  shape: rectangle
  style.fill: "#f8f8f8"
  style.stroke: "#333333"
}

result: 실행 결과 {
  style.border-radius: 8
  style.stroke-dash: 5
  style.stroke: "#333333"
  style.fill: "#f8f8f8"

  ca: 컨테이너 A {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
  cb: 컨테이너 B {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
  cc: 컨테이너 C {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }

  ca <-> cb <-> cc {
    style.stroke: "#333333"
    style.stroke-dash: 3
  }
}

yml -> up -> result {
  style.stroke: "#333333"
}
