direction: right

minikube: 미니큐브 (단일 노드) {
  style.border-radius: 8
  style.stroke-dash: 5
  style.stroke: "#333333"
  style.fill: "#f8f8f8"

  cp: 컨트롤 플레인 {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
  wk: 워커 노드 {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }

  cp <-> wk {
    style.stroke: "#333333"
  }
}
