direction: right

yml: docker-compose.yml {
  shape: page
  style.fill: "#ffffff"
  style.stroke: "#333333"
}

r1: 컨테이너 생성 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}
r2: 네트워크 연결 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}
r3: 볼륨 마운트 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}
r4: 환경변수 주입 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}

yml -> r1 {
  style.stroke: "#333333"
}
yml -> r2 {
  style.stroke: "#333333"
}
yml -> r3 {
  style.stroke: "#333333"
}
yml -> r4 {
  style.stroke: "#333333"
}
