direction: right

pod-dead: Pod 비정상 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}

rs: ReplicaSet 감지 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}

pod-new: 새 Pod 자동 생성 {
  style.fill: "#ffffff"
  style.stroke: "#333333"
}

pod-dead -> rs: 상태 불일치 {
  style.stroke: "#333333"
}
rs -> pod-new: 자동 복구 {
  style.stroke: "#333333"
}
