direction: right

master: 컨트롤 플레인 {
  style.border-radius: 8
  style.stroke-dash: 5
  style.stroke: "#333333"
  style.fill: "#f8f8f8"
  api: Kube API Server {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
}

worker: 워커 노드 {
  style.border-radius: 8
  style.stroke-dash: 5
  style.stroke: "#333333"
  style.fill: "#f8f8f8"
  kl: kubelet {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
  pod: Pod {
    shape: circle
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
  kl -> pod: 생성/종료/재시작 {
    style.stroke: "#333333"
  }
}

master.api -> worker.kl: 작업 전달 {
  style.stroke: "#333333"
}
