direction: right

dev: 개발자 {
  shape: person
  style.stroke: "#333333"
  style.fill: "#f0f0f0"
}

master: 컨트롤 플레인 {
  style.border-radius: 8
  style.stroke-dash: 5
  style.stroke: "#333333"
  style.fill: "#f8f8f8"
  api: Kube API Server {
    style.fill: "#ffffff"
    style.stroke: "#333333"
  }
}

dev -> master.api: kubectl 명령 {
  style.stroke: "#333333"
}
